---

- name: Send email notification to GIS.lab administrator
  shell: >
    echo -e 'Dear GIS.lab Administrator,\ntesting of your system is successfully done.'
    | mail -s '[GIS.lab test: {{ GISLAB_TEST_UNIQUE_STRING }}]: Testing is done' root
  args:
    executable: /bin/bash
  ignore_errors: yes
  changed_when: False

- name: Testing of GIS.lab is done
  shell: date -R
  ignore_errors: yes
  changed_when: False

# vim: set ts=8 sts=2 sw=2 et:
