---

- name: Send email notification to GIS.lab administrator
  shell: "echo -e 'Dear GIS.lab Administrator,\ntesting of your system is successfully done.'
    | mail -s '[GIS.lab test: {{ GISLAB_TEST_UNIQUE_STRING }}]: Testing is done' root"
  args:
    executable: /bin/bash

- name: Testing of GIS.lab is done
  shell: date -R
  changed_when: False

# vim:ft=ansible:
