---

GISLAB_CLIENT_INSTALL_PACKAGES_KERNEL:
  # list of Linux kernel packages (installed without recommended packages)
  - linux-image-generic-lts-raring
  - linux-headers-generic-lts-raring


GISLAB_CLIENT_INSTALL_PACKAGES_DEFAULT:
  # list of basic desktop packages (installed with recommended packages)
  - acpi-support
  - alsa-base
  - alsa-utils
  - aptitude
  - avahi-autoipd
  - avahi-daemon
  - anacron
  - bc
  - ca-certificates
  - catfish
  - cups
  - cups-bsd
  - cups-client
  - curl
  - desktop-file-utils
  - dbus-x11
  - dmz-cursor-theme
  - doc-base
  - espeak
  - file-roller
  - fonts-liberation
  - fonts-opensymbol
  - foomatic-db-compressed-ppds
  - foomatic-filters
  - genisoimage
  - ghostscript-x
  - gstreamer0.10-gnomevfs
  - gstreamer0.10-plugins-base
  - gstreamer0.10-plugins-base-apps
  - gstreamer0.10-plugins-good
  - gstreamer0.10-pulseaudio
  - gstreamer0.10-tools
  - gtk2-engines
  - gtk2-engines-pixbuf
  - gvfs
  - gvfs-backends
  - gvfs-fuse
  - gvfs-bin
  - hplip
  - ibus
  - ibus-gtk
  - ibus-pinyin
  - ibus-pinyin-db-android
  - ibus-table
  - im-switch
  - indicator-application-gtk2
  - indicator-sound-gtk2
  - inputattach
  - jockey-gtk
  - laptop-detect
  - libasound2-plugins
  - libgd2-xpm
  - libnotify-bin
  - libnss-ldap
  - libnss-mdns
  - libpam-ck-connector
  - libpam-cracklib
  - libpam-gnome-keyring
  - libsasl2-modules
  - libxp6
  - lightdm
  - lightdm-gtk-greeter
  - mkelfimage
  - munin-node
  - nbd-client
  - nfs-common
  - nvidia-common
  - openprinting-ppds
  - openssh-server
  - pavucontrol
  - pcmciautils
  - policykit-desktop-privileges
  - printer-driver-c2esp
  - printer-driver-foo2zjs
  - printer-driver-min12xxw
  - printer-driver-pnm2ppa
  - printer-driver-ptouch
  - printer-driver-pxljr
  - printer-driver-sag-gdi
  - printer-driver-splix
  - rarian-compat
  - syslinux-common
  - speech-dispatcher
  - system-config-printer-gnome
  - thunar
  - thunar-volman
  - thunar-archive-plugin
  - thunar-media-tags-plugin
  - ttf-dejavu-core
  - ttf-freefont
  - ttf-ubuntu-font-family
  - tumbler
  - ubuntu-extras-keyring
  - udhcpc
  - unzip
  - wireless-tools
  - wpasupplicant
  - xcursor-themes
  - xdg-user-dirs
  - xdg-user-dirs-gtk
  - xdg-utils
  - xfce4-appfinder
  - xfce4-datetime-plugin
  - xfce4-indicator-plugin
  - xfce4-notifyd
  - xfce4-panel
  - xfce4-power-manager
  - xfce4-screenshooter
  - xfce4-session
  - xfce4-settings
  - xfce4-taskmanager
  - xfce4-terminal
  - xfce4-utils
  - xfce4-volumed
  - xfce4-xkb-plugin
  - xfdesktop4
  - xfwm4
  - xkb-data
  - xorg
  - xterm
  - xubuntu-artwork
  - xubuntu-default-settings
  - xul-ext-ubufox
  - zenity
  - zip


GISLAB_CLIENT_INSTALL_PACKAGES_OFFICE:
  # list of default office packages (installed without recommended packages)
  - conky-std
  - evince
  - firefox
  - firefox-gnome-support
  - flashplugin-installer
  - freerdp-x11
  - gcalctool
  - gdisk
  - gimp
  - gthumb
  - gtk-recordmydesktop
  - htop
  - imagemagick
  - inkscape
  - leafpad
  - keepassx
  - libreoffice
  - libreoffice-calc
  - libreoffice-gtk
  - libreoffice-writer
  - mc
  - mutt
  - pidgin
  - pidgin-libnotify
  - rst2pdf
  - sshfs
  - vim-gnome
  - vlc
  - vlc-plugin-pulse
  - x11vnc


GISLAB_CLIENT_INSTALL_PACKAGES_LAB:
  # list of GIS.lab client GIS packages (installed without recommended packages)
  - gdal-bin
  - git
  - grass7
  - ipython
  - josm
  - pgadmin3
  - postgresql-client
  - postgresql-comparator
  - proj-bin
  - python-pysqlite2
  - python-gdal
  - python-qgis
  - qgis
  - qgit
  - spatialite-bin
  - spatialite-gui
  - sqlite3


GISLAB_CLIENT_INSTALL_PACKAGES_DEVELOPMENT:
  # list of GIS.lab client development packages (installed without recommended packages)
  - bison
  - build-essential
  - ccache
  - cmake
  - doxygen
  - flex
  - g++
  - gcc
  - gdb
  - git
  - graphviz
  - grass-dev
  - libexpat1-dev
  - libfcgi-dev
  - libgdal1-dev
  - libgeos-dev
  - libgsl0-dev
  - libpq-dev
  - libproj-dev
  - libqtwebkit-dev
  - libqt4-dev
  - libqt4-opengl-dev
  - libqwt5-qt4-dev
  - libspatialindex-dev
  - libspatialite-dev
  - libsqlite3-dev
  - make
  - pkg-config
  - pyqt4-dev-tools
  - python
  - python-dev
  - python-gdal
  - python-qscintilla2
  - python-qt4
  - python-qt4-dev
  - python-sip
  - python-sip-dev
  - qgit
  - qt4-dev-tools
  - qt4-qmlviewer
  - txt2tags
  - xauth
  - xfonts-base


GISLAB_CLIENT_INSTALL_PACKAGES_WORKER:
  # OWS worker packages
  - lighttpd
  - python-gdal
  - python-qgis
  - qgis
  - qgis-mapserver
  - xvfb


GISLAB_CLIENT_REMOVE_PACKAGES:
  # List of packages which have been installed automatically as dependency but we don't want them to be installed.
  # Run  '$ aptitude why <package>' find out the reason why package was installed.
  - network-manager
  - network-manager-pptp
  - xscreensaver


apt_get_opts: "
 --assume-yes
 --force-yes"


# vim:ft=ansible:
