---

# get list of Ubuntu installer tasks: $ tasksel --list-tasks
# get list of packages included in task: $ tasksel --task-packages <task> 


GISLAB_CLIENT_INSTALL_PACKAGES_KERNEL:
  # list of Linux kernel packages (installed without recommended packages)
  - linux-image-generic-lts-raring
  - linux-headers-generic-lts-raring


GISLAB_CLIENT_INSTALL_PACKAGES_BASE:
  # list of basic server packages (installed with recommended packages)
  - acpid
  - acpi-support
  - apt-show-versions
  - bc
  - curl
  - genisoimage
  - libnss-ldap
  - libpam-ck-connector
  - libpam-cracklib
  - libsasl2-modules
  - mkelfimage
  - munin-node
  - nbd-client
  - nfs-common
  - openssh-server
  - rsyslog
  - syslinux-common
  - udhcpc
  - unzip
  - zip
  

GISLAB_CLIENT_INSTALL_PACKAGES_DESKTOP:
  # list of basic desktop packages (installed with recommended packages)
  - alsa-base
  - alsa-utils
  - aptitude
  - ca-certificates
  - catfish
  - desktop-file-utils
  - dbus-x11
  - dmz-cursor-theme
  - doc-base
  - file-roller
  - fonts-liberation
  - fonts-opensymbol
  - ghostscript-x
  - gstreamer0.10-gnomevfs
  - gstreamer0.10-plugins-base
  - gstreamer0.10-plugins-base-apps
  - gstreamer0.10-plugins-good
  - gstreamer0.10-pulseaudio
  - gstreamer0.10-tools
  - gtk2-engines
  - gtk2-engines-pixbuf
  - gvfs
  - gvfs-backends
  - gvfs-fuse
  - gvfs-bin
  - ibus
  - ibus-gtk
  - ibus-pinyin
  - ibus-pinyin-db-android
  - ibus-table
  - im-switch
  - indicator-application-gtk2
  - indicator-sound-gtk2
  - inputattach
  - laptop-detect
  - libasound2-plugins
  - libgd2-xpm
  - libnotify-bin
  - libpam-gnome-keyring
  - libxp6
  - lightdm
  - lightdm-gtk-greeter
  - nvidia-common
  - pavucontrol
  - pcmciautils
  - policykit-desktop-privileges
  - rarian-compat
  - thunar
  - thunar-volman
  - thunar-archive-plugin
  - thunar-media-tags-plugin
  - ttf-dejavu-core
  - ttf-freefont
  - ttf-ubuntu-font-family
  - tumbler
  - ubuntu-extras-keyring
  - wireless-tools
  - wpasupplicant
  - xcursor-themes
  - xdg-user-dirs
  - xdg-user-dirs-gtk
  - xdg-utils
  - xfce4-appfinder
  - xfce4-datetime-plugin
  - xfce4-indicator-plugin
  - xfce4-notifyd
  - xfce4-panel
  - xfce4-power-manager
  - xfce4-screenshooter
  - xfce4-session
  - xfce4-settings
  - xfce4-taskmanager
  - xfce4-terminal
  - xfce4-utils
  - xfce4-volumed
  - xfce4-xkb-plugin
  - xfdesktop4
  - xfwm4
  - xkb-data
  - xorg
  - xterm
  - xubuntu-artwork
  - xubuntu-default-settings
  - xul-ext-ubufox
  - zenity


GISLAB_CLIENT_INSTALL_PACKAGES_OFFICE:
  # list of default office packages (installed without recommended packages)
  - conky-std
  - cups
  - cups-bsd
  - cups-client
  - evince
  - firefox
  - firefox-gnome-support
  - flashplugin-installer
  - foomatic-db-compressed-ppds
  - foomatic-db-engine
  - foomatic-filters
  - freerdp-x11
  - libfreerdp-plugins-standard
  - gcalctool
  - gdisk
  - gimp
  - gthumb
  - gtk-recordmydesktop
  - htop
  - hplip
  - imagemagick
  - inkscape
  - leafpad
  - keepassx
  - libreoffice
  - libreoffice-calc
  - libreoffice-gtk
  - libreoffice-writer
  - mc
  - mutt
  - openprinting-ppds
  - pidgin
  - pidgin-libnotify
  - printer-driver-c2esp
  - printer-driver-foo2zjs
  - printer-driver-gutenprint
  - printer-driver-hpijs
  - printer-driver-min12xxw
  - printer-driver-pnm2ppa
  - printer-driver-postscript-hp
  - printer-driver-ptouch
  - printer-driver-pxljr
  - printer-driver-sag-gdi
  - printer-driver-splix
  - pssh
  - rst2pdf
  - system-config-printer-gnome
  - sshfs
  - vim-gnome
  - vlc
  - vlc-plugin-pulse
  - x11vnc
  - xtightvncviewer


GISLAB_CLIENT_INSTALL_PACKAGES_LAB:
  # list of GIS.lab client GIS packages (installed without recommended packages)
  - gdal-bin
  - git
  - grass7
  - grass7-doc
  - ipython
  - josm
  - pgadmin3
  - postgresql-client
  - postgresql-comparator
  - proj-bin
  - python-pysqlite2
  - python-gdal
  - python-qgis
  - qgis
  - qgit
  - spatialite-bin
  - spatialite-gui
  - sqlite3


GISLAB_CLIENT_INSTALL_PACKAGES_WORKER:
  # OWS worker packages
  - lighttpd
  - python-gdal
  - python-qgis
  - qgis
  - qgis-mapserver
  - xvfb


GISLAB_CLIENT_REMOVE_PACKAGES:
  # List of packages which have been installed automatically as dependency but we don't want them to be installed.
  # Run  '$ aptitude why <package>' find out the reason why package was installed.
  - network-manager
  - network-manager-pptp
  - xscreensaver


apt_get_opts: "
 --assume-yes
 --force-yes"


# vim:ft=ansible:
