---

GISLAB_CLIENT_INSTALL_PACKAGES_DEFAULT:
  # list of XUbuntu required packages (installed with recommended packages)
  - alsa-base
  - alsa-utils
  - anacron
  - bc
  - ca-certificates
  - dmz-cursor-theme
  - doc-base
  - foomatic-db-compressed-ppds
  - foomatic-filters
  - genisoimage
  - ghostscript-x
  - gtk2-engines
  - gtk2-engines-pixbuf
  - inputattach
  - libasound2-plugins
  - libgd2-xpm
  - libnss-ldap
  - libpam-ck-connector
  - libsasl2-modules
  - libxp6
  - lightdm
  - lightdm-gtk-greeter
  - nvidia-common
  - openprinting-ppds
  - printer-driver-pnm2ppa
  - rarian-compat
  - rfkill
  - thunar
  - thunar-volman
  - ttf-dejavu-core
  - ttf-freefont
  - tumbler
  - ubuntu-extras-keyring
  - unzip
  - wireless-tools
  - wpasupplicant
  - xdg-user-dirs
  - xdg-user-dirs-gtk
  - xfce4-appfinder
  - xfce4-notifyd
  - xfce4-panel
  - xfce4-session
  - xfce4-settings
  - xfce4-utils
  - xfdesktop4
  - xfwm4
  - xkb-data
  - xorg
  - xterm
  - xubuntu-artwork
  - xubuntu-default-settings
  - zenity
  - zip
  # list of XUbuntu recommended packages
  - acpi-support
  - apport-gtk
  - avahi-autoipd
  - avahi-daemon
  - catfish
  - cups
  - cups-bsd
  - cups-client
  - desktop-file-utils
  - espeak
  - evince
  - file-roller
  - firefox
  - firefox-gnome-support
  - fonts-kacst-one
  - fonts-khmeros-core
  - fonts-lao
  - fonts-liberation
  - fonts-nanum
  - fonts-opensymbol
  - fonts-takao-pgothic
  - fonts-thai-tlwg
  - gcalctool
  - gcc
  - gimp
  - gstreamer0.10-plugins-base-apps
  - gstreamer0.10-pulseaudio
  - gthumb
  - gucharmap
  - gvfs-backends
  - gvfs-fuse
  - hplip
  - ibus
  - ibus-gtk
  - ibus-pinyin
  - ibus-pinyin-db-android
  - ibus-table
  - im-switch
  - indicator-application-gtk2
  - indicator-sound-gtk2
  - jockey-gtk
  - kerneloops-daemon
  - laptop-detect
  - leafpad
  - libnotify-bin
  - libnss-mdns
  - libpam-gnome-keyring
  - make
  - pastebinit
  - pavucontrol
  - pcmciautils
  - pidgin
  - pidgin-microblog
  - policykit-desktop-privileges
  - printer-driver-c2esp
  - printer-driver-foo2zjs
  - printer-driver-min12xxw
  - printer-driver-ptouch
  - printer-driver-pxljr
  - printer-driver-sag-gdi
  - printer-driver-splix
  - speech-dispatcher
  - system-config-printer-gnome
  - thunar-archive-plugin
  - thunar-media-tags-plugin
  - ttf-indic-fonts-core
  - ttf-punjabi-fonts
  - ttf-ubuntu-font-family
  - ttf-wqy-microhei
  - xcursor-themes
  - xdg-utils
  - xfce4-cpugraph-plugin
  - xfce4-datetime-plugin
  - xfce4-indicator-plugin
  - xfce4-mailwatch-plugin
  - xfce4-netload-plugin
  - xfce4-notes-plugin
  - xfce4-places-plugin
  - xfce4-power-manager
  - xfce4-quicklauncher-plugin
  - xfce4-screenshooter
  - xfce4-systemload-plugin
  - xfce4-taskmanager
  - xfce4-terminal
  - xfce4-verve-plugin
  - xfce4-volumed
  - xfce4-weather-plugin
  - xfce4-xkb-plugin
  - xubuntu-docs
  - xul-ext-ubufox


GISLAB_CLIENT_INSTALL_PACKAGES_GIS:
  # list of GIS.lab client extra packages (installed without recommended packages)
  - aptitude
  - conky-std
  - curl
  - flashplugin-installer
  - freerdp-x11
  - gdal-bin
  - gdisk
  - gimp
  - git
  - git-core
  - grass7
  - gthumb
  - gtk-recordmydesktop
  - htop
  - imagemagick
  - inkscape
  - ipython
  - josm
  - keepassx
  - libgdal1h
  - libreoffice
  - libreoffice-calc
  - libreoffice-gtk
  - libreoffice-writer
  - lightdm-gtk-greeter
  - mc
  - mkelfimage
  - nbd-client
  - nfs-common
  - openssh-server
  - pgadmin3
  - postgresql-client
  - postgresql-comparator
  - proj-bin
  - python-pysqlite2
  - python-gdal
  - python-qgis
  - qgis
  - qgit
  - rst2pdf
  - spatialite-bin
  - spatialite-gui
  - sqlite3
  - sshfs
  - syslinux-common
  - udhcpc
  - vim-gnome
  - vlc
  - vlc-plugin-pulse
  - x11vnc
  - xvfb

# List of GIS.lab client development packages (installed without recommended packages)
GISLAB_CLIENT_GIS_DEVELOPMENT_PACKAGES:
  - bison
  - build-essential
  - ccache
  - cmake
  - doxygen
  - flex
  - g++
  - gdb
  - git
  - graphviz
  - grass-dev
  - libexpat1-dev
  - libfcgi-dev
  - libgdal1-dev
  - libgeos-dev
  - libgsl0-dev
  - libpq-dev
  - libproj-dev
  - libqtwebkit-dev
  - libqt4-dev
  - libqt4-opengl-dev
  - libqwt5-qt4-dev
  - libspatialindex-dev
  - libspatialite-dev
  - libsqlite3-dev
  - make
  - pkg-config
  - pyqt4-dev-tools
  - python
  - python-dev
  - python-gdal
  - python-qscintilla2
  - python-qt4
  - python-qt4-dev
  - python-sip
  - python-sip-dev
  - qgit
  - qgit
  - qt4-dev-tools
  - qt4-qmlviewer
  - txt2tags
  - xauth
  - xfonts-base

# List of packages to remove client images.
# To find out the reason why package was installed use '$ aptitude why <package>'.
GISLAB_CLIENT_REMOVE_PACKAGES:
  - network-manager
  - network-manager-gnome
  - network-manager-pptp
  - network-manager-pptp-gnome


apt_get_opts: "
 --assume-yes
 --force-yes"

# vim:ft=ansible:
