---

# I was trying to test DHCP server using udhcpc client and dhcping. It seems, that both can't work when client and
# server is the same machine:
# * $ busybox udhcpc -i eth1 -s /tmp/test.sh
# * $ dhcping -V -c 192.168.15.5 -s 192.168.15.5


# vim:ft=ansible:
