---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

script:
  - ansible-playbook -i inventories/localhost system/gislab.yml --syntax-check
  - "ansible-playbook -i inventories/localhost system/gislab.yml --connection=local --sudo"
  - "ansible-playbook -i inventories/localhost system/test.yml --connection=local --sudo"
