---
language: python
python: "2.7"

before_install:
  # Print network configuration
  - sudo ip addr show

  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

script:
  - "ansible-playbook -i inventories/localhost --extra-vars 'GISLAB_ADMIN_PASSWORD=gislab' system/gislab.yml --syntax-check"
  - "ansible-playbook -i inventories/localhost --extra-vars 'GISLAB_ADMIN_PASSWORD=gislab' -vv system/gislab.yml --connection=local --sudo"
  - "ansible-playbook -i inventories/localhost -vv system/test.yml --connection=local --sudo"
