---

sudo: required
dist: trusty
language: generic


before_install:
  ### ENVIRONMENT
  - sudo free
  - sudo ps aux

  ### OS
  - sudo apt-get --assume-yes --force-yes install software-properties-common
  - sudo apt-add-repository --yes ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get --assume-yes --force-yes install ansible

  ### VIRTUALBOX
  - wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian trusty contrib" > /etc/apt/sources.list.d/virtualbox.list'
  - sudo apt-get update
  - sudo apt-get --assume-yes --force-yes install build-essential linux-headers-$(uname -r) dkms
  - sudo apt-get --assume-yes --force-yes install virtualbox-5.0

  ### VAGRANT
  - wget https://releases.hashicorp.com/vagrant/1.7.4/vagrant_1.7.4_x86_64.deb
  - sudo dpkg -i vagrant_1.7.4_x86_64.deb
  - sudo apt-get --fix-missing install

    # use 32-bit, because running 64-bit OS is not supported in nested VM
  - vagrant box add precise-canonical http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-i386-vagrant-disk1.box

script:
  - "echo 'GISLAB_ADMIN_PASSWORD: gislab\nGISLAB_DEBUG_INSTALL: yes' > system/host_vars/gislab_vagrant"
  - vagrant up
