---

- name: Test GIS.lab Web QGIS plugins repository
  shell: >
    curl "http://server.gis.lab/qgis/gislab-web.xml"
    | grep "xml version = '1.0' encoding = 'UTF-8'"
  ignore_errors: yes
  changed_when: False

- name: Test if QGIS plugin is downloadable from QGIS plugins repository
  shell: >
    curl -I
    $(curl "http://server.gis.lab/qgis/gislab-web.xml"
    | grep "download_url"
    | head -n 1
    | sed -e 's/<[^>]*>//g')
    | grep "Content-Type: application/zip"
  ignore_errors: yes
  changed_when: False


- name: Test if GIS.lab Web client is running with empty project
  shell: >
    curl -k -I "https://web.gis.lab"
    | grep "HTTP/1.1 200 OK"
  ignore_errors: yes
  changed_when: False

- name: Test GIS.lab Web API request
  shell: >
    curl -k "https://web.gis.lab/gislab_version.json"
    | grep "GISLAB_UNIQUE_ID"
  ignore_errors: yes
  changed_when: False

# vim: set ts=8 sts=2 sw=2 et:
