---
# Build GIS.lab Mobile client package for Android.

- hosts: all
  sudo: yes

  vars:
    # OS
    packages:
      - ant
      - expect
      - openjdk-7-jdk

    # Android
    android_sdk_url_base: http://dl.google.com/android
    android_sdk_version: 24.1.2
    android_build_tools_version: 22.0.1
    android_api_version: 22
    android_root: /build/android-sdk-linux

    # NodeJS
    nodejs_url_base: http://nodejs.org/dist
    nodejs_version: 0.10.32
    nodejs_root: /build/nodejs

    # Cordova
    cordova_version: 5.1.1

    # GIS.lab Mobile
    gislab_mobile_root: /build/gislab-mobile

    wget_opts: "
    --continue
    --no-verbose
    --retry-connrefused
    --waitretry=1
    --read-timeout=20
    --timeout=15
    --tries=0"

  tasks:
    ### BASIC OS
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install aptitude which is required for running system upgrade
      apt:
        pkg: aptitude
        force: yes
        install_recommends: no
        state: latest

    - name: Upgrade system
      apt:
        upgrade: full
        force: yes

    - name: Install packages
      apt:
        pkg: "{{ packages }}"
        force: yes
        install_recommends: no
        state: latest


    # locale
    - name: Generate locale
      locale_gen:
        name: en_US.UTF-8
        state: present


    ### DEPENDENCIES
    # android SDK
    - name: Create GIS.lab Mobile build directory
      shell: rm -rf {{ gislab_mobile_root }}

    - name: Install script for non-interactive Android platform, tools and API installation
      copy:
        content: |
          #!/usr/bin/expect

          set timeout -1;
          spawn {{ android_root }}/tools/android update sdk \
          --no-ui \
          --all \
          --filter platform-tools,build-tools-{{ android_build_tools_version }},android-{{ android_api_version }};
          expect {
          "Do you accept the license" { exp_send "y\r" ; exp_continue }
          eof
          }
        dest: /build/android-sdk-install.expect

    - name: Download Android SDK
      command: >
        wget {{ wget_opts }} {{ android_sdk_url_base }}/android-sdk_r{{ android_sdk_version }}-linux.tgz

    - name: Install Android SDK
      command: >
        tar -xzf
        android-sdk_r{{ android_sdk_version }}-linux.tgz
        -C /build/
      args:
        creates: /build/android-sdk-linux/tools/android

    - name: Install Android platform, tools and API
      command: >
        expect /build/android-sdk-install.expect
      args:
        creates: /build/android-sdk-linux/platform-tools/adb


    # nodeJS
    # TODO: use NVM
    - name: Download NodeJS
      command: >
        wget {{ wget_opts }} {{ nodejs_url_base }}/v{{ nodejs_version }}/node-v{{ nodejs_version }}-linux-x86.tar.gz

    - name: Install NodeJS
      command: >
        tar -xzf
        node-v{{ nodejs_version }}-linux-x86.tar.gz
        -C /build/
      args:
        creates: /build/nodejs/bin/node

    - name: Rename NodeJS directory
      command: >
        mv /build/node-v{{ nodejs_version }}-linux-x86 /build/nodejs
      args:
        creates: /build/nodejs/bin/node


    # cordova
    - name: Install Cordova
      command: >
        {{ nodejs_root }}/bin/npm install
        --quiet
        --cache=cache-npm
        --global
        cordova@{{ cordova_version }}


    ### PACKAGE BUILD
    - name: Copy GIS.lab Mobile files
      command: >
        cp -a /vagrant {{ gislab_mobile_root }}

    - name: Build GIS.lab Mobile package
      shell: >
        export
        PATH=$PATH:{{ android_root }}/tools:{{ android_root }}/platform-tools:{{ nodejs_root }}/bin
        ANDROID_HOME={{ android_root }}
        ANDROID_BUILD=ant
        &&
        cordova platform add android
        &&
        node tasks/plugins.js
        &&
        cordova build android
      args:
        chdir: "{{ gislab_mobile_root }}"


    - name: Get GIS.lab Mobile version
      shell: >
        grep "widget id=\"io.gislab.mobile\"" config.xml
        | awk -F " " '{print $3}'
        | awk -F "=" '{print $2}'
        | sed  's/"//g'
      args:
        chdir: "{{ gislab_mobile_root }}"
      register: gislab_mobile_version

    - name: Move GIS.lab Mobile package to shared directory
      # Cordova is currently not capable to build APK with correct file name in
      # correct directory. It is changing from release to release
      # (see: https://issues.apache.org/jira/browse/CB-7827)
      shell: >
        find /build/gislab-mobile
        -name '*-debug.apk'
        -type f
        -exec mv '{}' /vagrant/gislab-mobile-{{ gislab_mobile_version.stdout }}.apk \;
      args:
        executable: /bin/bash

# vim: set ts=8 sts=2 sw=2 et:
