---
#
### Build GIS.lab Desktop client image for LAN
#

- name: Install packages (default provider)
  apt:
    pkg: "{{ item }}"
    force: yes
    install_recommends: no
    state: latest
  with_items:
    - squashfs-tools


### PXE BOOT
- name: Install PXE support files
  command: >
    cp
    {{ root_dir }}/root{{ item.src }}
    {{ root_dir }}/root{{ item.dest }}
  with_items:
    - {
        src: "/usr/lib/syslinux/pxelinux.0",
        dest: "/boot/pxelinux.0"
      }
    - {
        src: "/usr/lib/syslinux/gpxelinux.0",
        dest: "/boot/gpxelinux.0"
      }

- name: Create PXE boot configuration directory
  file:
    dest: "{{ root_dir }}/root/boot/pxelinux.cfg"
    state: directory

- name: Install PXE configuration file
  template:
    src: pxe-boot/gislab.j2
    dest: "{{ root_dir }}/root/boot/pxelinux.cfg/default"


### HTTP BOOT
# To boot via HTTP, client machine must boot iPXE boot image first. This boot
# image will launch HTTP boot. Prepared iPXE boot loader image file exists in
# 'http-boot/gislab-bootloader.iso'.
- name: Install ramdisk and kernel files for HTTP boot
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - {
        src: "/var/lib/tftpboot/gislab/vmlinuz",
        dest: "/var/www/default/vmlinuz"
      }
    - {
        src: "/var/lib/tftpboot/gislab/initrd.img",
        dest: "/var/www/default/initrd.img"
      }


### IMAGE
- name: Build GIS.lab client image
  shell: gislab-client-image > /dev/null
  args:
    executable: /bin/bash
  notify:
    - service nbd-server restart


- meta: flush_handlers

# vim: set ts=8 sts=2 sw=2 et:
