---
#
### Build GIS.lab Desktop client image for LAN
#

- name: Install packages (default provider)
  apt:
    pkg: "{{ item }}"
    force: yes
    install_recommends: no
    state: latest
  with_items:
    - squashfs-tools


### IMAGE
- name: Build GIS.lab client image
  shell: gislab-client-image > /dev/null
  args:
    executable: /bin/bash


- meta: flush_handlers

# vim: set ts=8 sts=2 sw=2 et:
