---
#
### GIS.lab MOBILE CLIENT ###
#
# Install GIS.lab Mobile client package.


- name: Create GIS.lab Mobile root directory
  file:
    dest: "{{ root_dir }}/apk"
    state: directory


- name: Download GIS.lab Mobile installer
  shell: >
    wget {{ wget_opts }}
    -O {{ GISLAB_PATH_CACHE }}/packages/apk/gislab-mobile-{{ gislab_mobile_version }}.apk
    {{ gislab_packages_url }}/gislab-mobile-{{ gislab_mobile_version }}.apk

- name: Install GIS.lab Mobile installer
  shell: >
    cp
    {{ GISLAB_PATH_CACHE }}/packages/apk/gislab-mobile-{{ gislab_mobile_version }}.apk
    {{ root_dir }}/apk/gislab-mobile.apk


- name: Create directory for publishing of GIS.lab Mobile installer
  file:
    dest: /var/www/default/clients/mobile
    recurse: yes
    state: directory

- name: Publish GIS.lab Mobile installer
  file:
    src: "{{ root_dir }}/apk/gislab-mobile.apk"
    dest: /var/www/default/clients/mobile/gislab-mobile.apk
    state: link
    force: yes

# vim: set ts=8 sts=2 sw=2 et:
