---

root_dir: "{{ GISLAB_PATH_SYSTEM }}/clients/mobile"

gislab_packages_url: http://imincik-software.s3.amazonaws.com

gislab_mobile_version: 0.1.0

wget_opts: "
  --continue
  --no-verbose
  --retry-connrefused
  --waitretry=1
  --read-timeout=20
  --timeout=15
  --tries=0"

# vim: set ts=8 sts=2 sw=2 et:
