---
#
### FILE SERVER - NFS ###
#
# Install and configure file sharing server.


- name: Install packages
  apt: pkg={{item}} force=yes install_recommends=no state=latest
  with_items:
    - nfs-kernel-server


# Shared directories
- name: Create 'repository' mount directory (readable for all, writable only for gislabadmins)
  file: path=/storage/repository state=directory owner=root group=gislabadmins mode=0775

- name: Create 'barrel' mount directory (readable and writable for all gislabusers)
  file: path=/storage/barrel state=directory owner=root group=nogroup mode=0775

- name: Create 'publish' mount directory (readable for file owners and www-data, writable for file owners)
  file: path=/storage/publish state=directory owner=root group=root mode=0755


# NFS configuration
- name: Configure NFS exports
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: "nfs/nfs-common.j2", dest: "/etc/default/nfs-common" }
    - { src: "nfs/nfs-kernel-server.j2", dest: "/etc/default/nfs-kernel-server" }
    - { src: "nfs/exports.j2", dest: "/etc/exports" }
  notify:
    - service gssd restart
    - service nfs-kernel-server restart

# Bind mount
- name: Configure to mount shares also to /mnt directory to keep the same paths as on clients
  lineinfile: dest=/etc/fstab line="/storage  /mnt  none  bind  0  0" state=present

- name: Mount /mnt
  mount: name=/mnt src=/storage fstype=none opts=bind state=mounted


- meta: flush_handlers

# vim:ft=ansible:
