---
#
### FILE SERVER - NFS ###
#
# Install and configure file sharing server.


- name: Install packages
  apt: pkg={{item}} force=yes install_recommends=no state=latest
  with_items:
    - nfs-kernel-server


# Shared directories
- name: Create 'repository' mount directory (readable for all, writable only for labadmins)
  file: path=/storage/repository state=directory owner=root group=labadmins mode=0775

- name: Create 'share' mount directory (readable for all, writable for file owners or labadmins)
  file: path=/storage/share state=directory owner=root group=labadmins mode=0775

- name: Create 'barrel' mount directory (readable and writable for all labusers)
  file: path=/storage/barrel state=directory owner=root group=nogroup mode=0775


# NFS configuration
- name: Configure NFS exports
  template: src=nfs/exports.j2 dest=/etc/exports
  notify:
    - service nfs-kernel-server restart

- name: Configure user IDs mapping
  template: src=nfs/idmapd.conf.j2 dest=/etc/idmapd.conf
  notify:
    - service idmapd restart


# Bind mount
- name: Configure to mount shares also to /mnt directory to keep the same paths as on clients
  lineinfile: dest=/etc/fstab line="/storage  /mnt  none  bind  0  0" state=present

- name: Mount /mnt
  mount: name=/mnt src=/storage fstype=none opts=bind state=mounted


- meta: flush_handlers
