---
#
### FILE SERVER - NFS ###
#
# Install and configure file sharing server.


- name: Install packages
  apt:
    pkg: "{{ item }}"
    force: yes
    install_recommends: no
    state: latest
  with_items:
    - nfs-kernel-server


### SHARED DIRECTORIES
# repository - readable for all, writable only for gislabadmins
- name: Create 'repository' mount directory
  file:
    path: "{{ GISLAB_PATH_STORAGE }}/repository"
    state: directory
    owner: root
    group: gislabadmins
    mode: 0775

# publish - readable for file owners and www-data, writable for file owners
- name: Create 'publish' mount directory
  file:
    path: "{{ GISLAB_PATH_STORAGE }}/publish"
    state: directory
    owner: root
    group: root
    mode: 0755

# barrel - readable and writable for all gislabusers
- name: Create 'barrel' mount directory
  file:
    path: "{{ GISLAB_PATH_STORAGE }}/barrel"
    state: directory
    owner: root
    group: nogroup
    mode: 0775


### NFS CONFIGURATION
- name: Configure NFS exports
  template:
    src: nfs/exports.j2
    dest: /etc/exports
  notify:
    - service nfs-kernel-server restart

- name: Configure user IDs mapping
  template:
    src: nfs/idmapd.conf.j2
    dest: /etc/idmapd.conf
  notify:
    - service idmapd restart


### BIND MOUNT
- name: Mount shares also to /mnt directory to keep the same paths as on clients
  lineinfile:
    dest: /etc/fstab
    line: "{{ GISLAB_PATH_STORAGE }}  /mnt  none  bind  0  0"
    state: present

- name: Mount /mnt
  mount:
    name: /mnt
    src: "{{ GISLAB_PATH_STORAGE }}"
    fstype: none
    opts: bind
    state: mounted


- meta: flush_handlers

# vim: set ts=8 sts=2 sw=2 et:
