---
#
### DATA ###
#
# Install user data placed in 'user' directory.


- name: Install user data
  copy: src=../user dest={{ GISLAB_ROOT }}

- name: Set executable permissions for plugins
  shell: "{{ item }}"
  with_items:
    - chmod -R 0775 {{ GISLAB_INSTALL_USER_DATA_ROOT }}/plugins/server
    - chmod -R 0775 {{ GISLAB_INSTALL_USER_DATA_ROOT }}/plugins/account

- name: Install user data in to 'Repository' share
  shell: "{{ item }}"
  with_items:
    - cp -a {{ GISLAB_INSTALL_USER_DATA_ROOT }}/data /storage/repository/
    - chown -R :labadmins /storage/repository/*

- name: Run user server plugins
  shell: "for plugin in {{ GISLAB_INSTALL_USER_DATA_ROOT }}/plugins/server/*.*; do
            GISLAB_INSTALL_ACTION={{ GISLAB_INSTALL_ACTION }} $plugin;
            echo '{{ GISLAB_INSTALL_DATETIME }} {{ GISLAB_INSTALL_ACTION }}' >> /var/lib/gislab/server-plugin-$(basename $plugin).done;
          done"
  args:
    executable: /bin/bash
