---
#
### DATA ###
#
# Install user data placed in 'user' directory.


- name: Install user data in to 'Repository' shared folder
  copy: src=../user/data/ dest=/storage/repository/

- name: Set permissions for 'Repository' shared folder
  shell: chown -R :labadmins /storage/repository/*
