---
#
### MAPSERVER ###
#
# Install and configure OWS server (mapserver).


- name: Install packages
  apt: pkg={{item}} force=yes install_recommends=no state=latest
  with_items:
    - apache2
    - apache2-mpm-worker
    - libapache2-mod-fcgid
    - qgis-mapserver


# Apache modules
- name: Enable 'rewrite' and 'exipres' Apache modules
  command: "{{ item }}"
  with_items:
    - a2enmod rewrite
    - a2enmod expires
  notify:
    - service apache2 restart


# Mapserver
- name: Configure Mapserver virtualhost
  template: src=apache2/site-mapserver.j2 dest=/etc/apache2/sites-available/mapserver
  notify:
    - service apache2 restart

- name: Enable Mapserver virtualhost
  command: a2ensite mapserver
  notify:
    - service apache2 restart


- meta: flush_handlers
