---
#
### BASIC SERVER CONFIGURATION ###
#
# Run basic server configuration.


# Facts
- name: Set GIS.lab installation root directory
  set_fact:
    GISLAB_ROOT: /opt/gislab

- name: Set GIS.lab worker installation root directory
  set_fact:
    GISLAB_INSTALL_WORKER_ROOT: "{{ GISLAB_ROOT }}/system/worker"

- name: Set GIS.lab client installation root directory
  set_fact:
    GISLAB_INSTALL_CLIENT_ROOT: "{{ GISLAB_ROOT }}/system/client"

- name: Set GIS.lab user account installation root directory
  set_fact:
    GISLAB_INSTALL_ACCOUNT_ROOT : "{{ GISLAB_ROOT }}/system/account"

- name: Set GIS.lab user data installation root directory
  set_fact:
    GISLAB_INSTALL_USER_DATA_ROOT: "{{ GISLAB_ROOT }}/user"


- name: Detect current date and time
  set_fact:
    GISLAB_INSTALL_DATETIME: "{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"

- name: Detect provisioning user name
  set_fact:
    GISLAB_PROVISIONING_USER: "{{ ansible_ssh_user }}"

- name: Detect architecture
  set_fact:
    GISLAB_SERVER_ARCHITECTURE: "{{ ansible_architecture }}"

- name: Detect if GIS.lab server network device is eth0
  set_fact:
    GISLAB_SERVER_NETWORK_DEVICE: eth0
  when: ansible_eth0.active and not ansible_eth1.active

- name: Detect if GIS.lab server network device is eth1
  set_fact:
    GISLAB_SERVER_NETWORK_DEVICE: eth1
  when: ansible_eth0.active and ansible_eth1.active

- name: Set GISLAB_SERVER_IP from eth0 if this is only one network device
  set_fact:
    GISLAB_SERVER_IP: "{{ ansible_eth0.ipv4.address }}"
  when: ansible_eth0.active and not ansible_eth1.active

- name: Set GISLAB_SERVER_IP from eth1 if exists
  set_fact:
    GISLAB_SERVER_IP: "{{ ansible_eth1.ipv4.address }}"
  when: ansible_eth0.active and ansible_eth1.active


# Configuration and basic directory structure
- name: Save current GIS.lab configuration to '/etc/gislab_version' file
  copy: content='
    GISLAB_ROOT="{{ GISLAB_ROOT }}"\n
    GISLAB_UNIQUE_ID="{{ GISLAB_UNIQUE_ID }}"\n
    GISLAB_SUITE="{{ GISLAB_SUITE }}"\n
    GISLAB_TIMEZONE="{{ GISLAB_TIMEZONE }}"\n
    GISLAB_APT_REPOSITORY_COUNTRY_MIRROR="{{ GISLAB_APT_REPOSITORY_COUNTRY_MIRROR }}"\n
    GISLAB_APT_HTTP_PROXY="{{ GISLAB_APT_HTTP_PROXY }}"\n
    GISLAB_LOGO="{{ GISLAB_LOGO }}"\n
    GISLAB_WALLPAPER="{{ GISLAB_WALLPAPER }}"\n
    GISLAB_NETWORK="{{ GISLAB_NETWORK }}"\n
    GISLAB_SERVER_IP="{{ GISLAB_SERVER_IP }}"\n
    GISLAB_SERVER_EMAIL_RELAY_SERVER="{{ GISLAB_SERVER_EMAIL_RELAY_SERVER }}"\n
    GISLAB_CLIENT_LANGUAGES="{{ GISLAB_CLIENT_LANGUAGES|join(",") }}"\n
    GISLAB_UNKNOWN_MAC_POLICY="{{ GISLAB_UNKNOWN_MAC_POLICY }}"\n
    GISLAB_CLIENTS_ALLOWED="{{ GISLAB_CLIENTS_ALLOWED|join(",") }}"\n
    GISLAB_CLIENT_INSTALL_PACKAGES="{{ GISLAB_CLIENT_INSTALL_PACKAGES|join(" ") }}"\n
    GISLAB_CLIENT_VIRTUALBOX_SUPPORT="{{ GISLAB_CLIENT_VIRTUALBOX_SUPPORT }}"\n
    GISLAB_CLIENT_VIRTUALBOX_ADDITIONS_ISO="{{ GISLAB_CLIENT_VIRTUALBOX_ADDITIONS_ISO }}"\n
    GISLAB_CLIENT_NETWORK_STORAGE="{{ GISLAB_CLIENT_NETWORK_STORAGE }}"\n
    GISLAB_CLIENT_LOAD_BALANCER_ENABLED="{{ GISLAB_CLIENT_LOAD_BALANCER_ENABLED }}"\n
    GISLAB_VERSION="{{ GISLAB_VERSION }}"\n
    GISLAB_SERVER_GUI_CONSOLE="{{ GISLAB_SERVER_GUI_CONSOLE }}"\n
    GISLAB_DEBUG_INSTALL="{{ GISLAB_DEBUG_INSTALL }}"\n
    GISLAB_DEBUG_SERVICES="{{ GISLAB_DEBUG_SERVICES }}"\n
    GISLAB_CLIENT_GIS_DEVELOPMENT_SUPPORT="{{ GISLAB_CLIENT_GIS_DEVELOPMENT_SUPPORT }}"\n
    GISLAB_QGIS_REPOSITORY="{{ GISLAB_QGIS_REPOSITORY }}"\n
    GISLAB_INSTALL_WORKER_ROOT="{{ GISLAB_INSTALL_WORKER_ROOT }}"\n
    GISLAB_INSTALL_CLIENT_ROOT="{{ GISLAB_INSTALL_CLIENT_ROOT }}"\n
    GISLAB_INSTALL_ACCOUNT_ROOT="{{ GISLAB_INSTALL_ACCOUNT_ROOT }}"\n
    GISLAB_INSTALL_USER_DATA_ROOT="{{ GISLAB_INSTALL_USER_DATA_ROOT }}"\n
    GISLAB_INSTALL_DATETIME="{{ GISLAB_INSTALL_DATETIME }}"\n
    GISLAB_PROVISIONING_USER="{{ GISLAB_PROVISIONING_USER }}"\n
    GISLAB_SERVER_ARCHITECTURE="{{ GISLAB_SERVER_ARCHITECTURE }}"\n
    GISLAB_SERVER_NETWORK_DEVICE="{{ GISLAB_SERVER_NETWORK_DEVICE }}"'
    dest="/etc/gislab_version"

- name: Create main GIS.lab installation directories structure
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ GISLAB_ROOT }}"
    - "{{ GISLAB_INSTALL_WORKER_ROOT }}"
    - "{{ GISLAB_INSTALL_CLIENT_ROOT }}"
    - "{{ GISLAB_INSTALL_ACCOUNT_ROOT }}"
    - "{{ GISLAB_INSTALL_USER_DATA_ROOT }}"
    - /var/lib/gislab


# Basic server configuration
- name: Add GISLAB_ROOT variable to server's environment
  lineinfile: dest=/etc/environment line="GISLAB_ROOT={{ GISLAB_ROOT }}" state=present

- name: Set hostname
  hostname: name=server

- name: Update hosts file
  template: src=hosts.j2 dest=/etc/hosts
  notify:
    - service rsyslog restart

- name: Generate en_US.UTF-8 locale
  locale_gen: name=en_US.UTF-8 state=present

- name: Set timezone
  template: src=timezone.j2 dest=/etc/timezone
  notify:
    - reconfigure timezone

- name: Set local aliases table
  template: src=aliases.j2 dest=/etc/aliases

- meta: flush_handlers


# Apt
- name: Configure apt repositories
  template: src=apt/sources.list.j2 dest=/etc/apt/sources.list

- name: Add imincik PPA signing key
  apt_key: id=6CD44B55 url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x25B546906CD44B55 state=present

- name: Add other apt signing keys
  apt_key: url="{{ item }}" state=present
  with_items:
    - http://josm.openstreetmap.de/josm-apt.key
    - https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Activate apt cache server if configured
  lineinfile: dest=/etc/apt/apt.conf.d/02proxy line='Acquire::http { Proxy "{{ GISLAB_APT_HTTP_PROXY }}"; };' state=present create=yes
  when: GISLAB_APT_HTTP_PROXY|default(None) != None 

- name: Deactivate apt cache server if none configured
  lineinfile: dest=/etc/apt/apt.conf.d/02proxy regexp="." state=absent
  when: GISLAB_APT_HTTP_PROXY|default(None) == None

- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade system
  apt: upgrade=full force=yes

- name: Install packages
  apt: pkg={{item}} force=yes install_recommends=no
  with_items:
    - htop
    - mc
    - pwgen
    - tmux
    - vim


# SSH
- name: Create GIS.lab configuration directory for SSH keys
  file: path={{ GISLAB_ROOT }}/ssh state=directory

- name: Install insecure SSH key if no secure one found
  copy: src=insecure_ssh_key.pub dest={{ GISLAB_ROOT }}/ssh/gislab_ssh_public_key mode=0600
  when: GISLAB_SSH_PRIVATE_KEY|default(None) == None or GISLAB_SSH_PUBLIC_KEY|default(None) == None

- name: Install secure SSH key
  copy: src={{ GISLAB_SSH_PUBLIC_KEY }} dest={{ GISLAB_ROOT }}/ssh/gislab_ssh_public_key mode=0600
  when: GISLAB_SSH_PRIVATE_KEY|default(None) != None and GISLAB_SSH_PUBLIC_KEY|default(None) != None


# Shell
- name: Configure shell prompt system wide
  lineinfile:
    dest=/etc/profile
    regexp="^PS1=.*h\.GIS.lab(.*).*$"
    line='PS1="\[$(tput bold)\]\u@\h.GIS.lab({{ GISLAB_UNIQUE_ID }}):\w\\$\[$(tput sgr0)\] "'
    state=present


# MOTD
- name: Set MOTD welcome message
  template: src=motd/00-header.j2 dest=/etc/update-motd.d/00-header

- name: Remove not needed MOTD messages
  shell: rm -f {{ item }}
  with_items:
    - /etc/update-motd.d/*-help-text
    - /etc/update-motd.d/*-cloudguest
    - /etc/update-motd.d/*-release-upgrade
    - /etc/update-motd.d/*-hwe-eol

- name: Update MOTD
  shell: run-parts /etc/update-motd.d


# GIS.lab management tools
- name: Install GIS.lab shell functions library
  copy: src=functions.sh dest={{ GISLAB_ROOT }}/functions.sh

- name: Install GIS.lab management scripts
  copy: src=bin dest={{ GISLAB_ROOT }}/ mode=0774 group={{ GISLAB_PROVISIONING_USER }}

- name: Add GIS.lab management scripts on path
  lineinfile: dest=/etc/profile line="PATH=$PATH:{{ GISLAB_ROOT }}/bin" state=present
