---
#
### HAPROXY SERVER ###
#
# Install OWS services load balancer.
#
# Logging: /storage/log/syslog


- name: Install packages
  apt: pkg={{item}} force=yes install_recommends=no state=latest
  with_items:
    - haproxy


- name: Activate HAProxy server
  template: src=haproxy/haproxy.j2 dest=/etc/default/haproxy

# TODO: always start server (after restart) with empty list of workers
- name: Configure HAProxy server
  template: src=haproxy/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify:
    - service haproxy restart


- meta: flush_handlers

# vim:ft=ansible:
