---
#
### HAPROXY SERVER ###
#
# Install OWS server load balancer.
#
# Logging: /var/log/syslog


- name: Install packages
  apt: pkg={{item}} force=yes install_recommends=no state=latest
  with_items:
    - haproxy
    - unzip


# Serf
- name: Install Serf
  shell: source {{ GISLAB_ROOT }}/functions.sh && gislab_serf_install
  args:
    executable: /bin/bash

- name: Configure Serf
  template: src=serf/serf.conf.j2 dest=/etc/init/serf.conf
  notify:
    - service serf restart

- name: Create Serf configuration directory
  file: path=/etc/serf/bin state=directory

- name: Install Serf handlers scripts 
  copy: src=static/serf/bin/ dest=/etc/serf/bin mode=0774


# HAProxy
- name: Activate HAProxy server
  template: src=haproxy/haproxy.j2 dest=/etc/default/haproxy

# TODO: always start server (after restart) with empty list of workers
- name: Configure HAProxy server
  template: src=haproxy/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify:
    - service haproxy restart


- meta: flush_handlers

# vim:ft=ansible:
