---
#
### GIS.LAB WEB ###
#
# Install and configure GIS.lab Web application.
#
# Logging: /var/log/nginx/gislab-web-access.log /var/log/nginx/gislab-web-error.log /var/log/syslog


- name: Install packages
  apt: pkg={{item}} force=yes install_recommends=no state=latest
  with_items:
    - gcc
    - nginx
    - python-dateutil
    - python-dev
    - python-pip
    - python-psycopg2
    - python-virtualenv
    - pwgen
    - zip


# PostgreSQL
- name: Generate 'gislab_web' database user password (run only once)
  shell: pwgen -s -N 1 10 > /etc/gislab/gislab-web_db_user_password.txt && chmod 600 /etc/gislab/gislab-web_db_user_password.txt
  args:
    creates: /etc/gislab/gislab-web_db_user_password.txt

- name: Get 'gislab_web' database user password
  shell: cat /etc/gislab/gislab-web_db_user_password.txt
  register: gislab_web_db_user_password


- name: Create database 'gislab_web' if not exists
  postgresql_db: name=gislab_web encoding='UTF-8' template=template0 state=present
  sudo_user: postgres

- name: Create database user 'gislab_web' if not exists
  postgresql_user: name=gislab_web role_attr_flags=NOCREATEDB,NOCREATEROLE,NOSUPERUSER password={{ gislab_web_db_user_password.stdout }} state=present
  sudo_user: postgres


# Python virtual environment
- name: Re-create Python virtual environment
  shell: rm -rf /usr/local/python-virtualenvs/gislab-web;
    virtualenv --clear --quiet --system-site-packages /usr/local/python-virtualenvs/gislab-web

- name: Install Gunicorn
  pip: name=gunicorn version=19.1.1
       virtualenv=/usr/local/python-virtualenvs/gislab-web
       virtualenv_site_packages=yes
       state=present
  notify:
    - service gislab-web restart


# GIS.lab Web installation
- name: Copy GIS.lab Web installation files to temporary dir on server
  copy: src=static/gislab-web dest=/tmp/

- name: Install Web requirements
  pip: requirements=/tmp/gislab-web/requirements.txt
       virtualenv=/usr/local/python-virtualenvs/gislab-web
       extra_args="--download-cache=/var/cache/pip"
       virtualenv_site_packages=yes
       state=present
  notify:
    - service gislab-web restart

- name: Install GIS.lab Web
  shell: source /usr/local/python-virtualenvs/gislab-web/bin/activate
         && python /tmp/gislab-web/setup.py install
  args:
    executable: /bin/bash
  notify:
    - service gislab-web restart

# GIS.lab Web project
- name: Re-create Web project directory
  shell: rm -rf /var/www/gislab-web; mkdir -p /var/www/gislab-web

- name: Create media directory
  file: path=/storage/gislab-web-media state=directory owner=www-data group=www-data


- name: Generate secret key (run only once)
  shell: pwgen -sy 50 1 | sed 's/"/_/g' > /etc/gislab/gislab-web_secret_key.txt && chmod 600 /etc/gislab/gislab-web_secret_key.txt
  args:
    creates: /etc/gislab/gislab-web_secret_key.txt

- name: Get secret key
  shell: cat /etc/gislab/gislab-web_secret_key.txt
  register: gislab_web_secret_key


- name: Deploy GIS.lab Web project
# we do not use Ansible django_manage module because of missing 'template' option
  shell: source /usr/local/python-virtualenvs/gislab-web/bin/activate
         && django-admin.py startproject --template=/tmp/gislab-web/webgis/conf/project_template/ djproject /var/www/gislab-web
  args:
    executable: /bin/bash
  notify:
    - service gislab-web restart

- name: Install secrets
  template: src=gislab-web/settings_secret.py.j2 dest=/var/www/gislab-web/djproject/settings_secret.py
  notify:
    - service gislab-web restart

- name: Sync database
  django_manage: command=syncdb app_path=/var/www/gislab-web settings=djproject.settings virtualenv=/usr/local/python-virtualenvs/gislab-web
  notify:
    - service gislab-web restart

- name: Collect static files
  django_manage: command=collectstatic app_path=/var/www/gislab-web settings=djproject.settings virtualenv=/usr/local/python-virtualenvs/gislab-web
  notify:
    - service gislab-web restart


- name: Remove GIS.lab Web installation files from temporary dir on server
  file: path=/tmp/gislab-web state=absent


# GIS.lab Web servers
- name: Install Gunicorn startup script
  template: src=gunicorn/gunicorn.sh.j2 dest=/var/www/gislab-web/gunicorn.sh
  notify:
    - service gislab-web restart

- name: Add executable permissions for Gunicorn startup script
  command: chmod 755 /var/www/gislab-web/gunicorn.sh


- name: Generate self signed SSL certificate (run only once)
  shell: openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout /etc/gislab/gislab-web.key -out /etc/gislab/gislab-web.crt
         -subj "/C=GL/ST=GIS.lab/L=GIS.lab/O=GIS.lab/OU=GIS.lab/CN=GIS.lab"
         && chmod 600 /etc/gislab/gislab-web.key
         && chmod 600 /etc/gislab/gislab-web.crt
  args:
    executable: /bin/bash
    creates: /etc/gislab/gislab-web.crt

- name: Install SSL certificate
  shell: "{{ item }}"
  with_items:
    - mkdir -p /etc/nginx/ssl
    - cp /etc/gislab/gislab-web.key /etc/nginx/ssl/gislab-web.key
    - cp /etc/gislab/gislab-web.crt /etc/nginx/ssl/gislab-web.crt
  args:
    executable: /bin/bash


- name: Configure Nginx virtualhost
  template: src=nginx/site-gislab-web.j2 dest=/etc/nginx/sites-available/gislab-web
  notify:
    - service nginx restart

- name: Activate Nginx virtualhost web.gis.lab
  file: src=/etc/nginx/sites-available/gislab-web dest=/etc/nginx/sites-enabled/gislab-web state=link
  notify:
    - service nginx restart


- name: Configure GIS.lab Web service
  template: src=init/gislab-web.conf.j2 dest=/etc/init/gislab-web.conf
  notify:
    - service gislab-web restart

- name: Activate GIS.lab Web service
  file: src=/lib/init/upstart-job dest=/etc/init.d/gislab-web state=link
  notify:
    - service gislab-web restart


- name: Activate cache cleaning
  template: src=cron/gislab-clean-web.j2 dest=/etc/cron.d/gislab-clean-web


# GIS.lab Web plugin installation
- name: Copy GIS.lab Web plugin installation files to temporary dir on server
  copy: src=static/gislab-web-plugin dest=/tmp/

- name: Copy GIS.lab Web plugin metadata file to temporary dir on server
  template: src=gislab-web-plugin/metadata.txt.j2 dest=/tmp/gislab-web-plugin/gislab_web/metadata.txt


- name: Re-create Web plugin directory
  shell: rm -rf /var/www/gislab-web-plugin; mkdir -p /var/www/gislab-web-plugin

- name: Build GIS.lab Web plugin package
  shell: make zip
  args:
    executable: /bin/bash
    chdir: /tmp/gislab-web-plugin/gislab_web

- name: Install GIS.lab Web plugin package
  shell: "{{ item }}"
  with_items:
    - cp /tmp/gislab-web-plugin/gislab_web/gislab_web.zip /var/www/gislab-web-plugin/
    - cp /tmp/gislab-web-plugin/gislab_web/icon.png /var/www/gislab-web-plugin/
  args:
    executable: /bin/bash

- name: Install GIS.lab Web plugin repository file
  template: src=gislab-web-plugin/plugins.xml.j2 dest=/var/www/gislab-web-plugin/plugins.xml

- name: Remove GIS.lab Web plugin installation files from temporary dir on server
  file: path=/tmp/gislab-web-plugin state=absent


- name: Configure Nginx virtualhost qgis.gis.lab
  template: src=nginx/site-gislab-web-plugin.j2 dest=/etc/nginx/sites-available/gislab-web-plugin
  notify:
    - service nginx restart

- name: Activate Nginx virtualhost qgis.gis.lab
  file: src=/etc/nginx/sites-available/gislab-web-plugin dest=/etc/nginx/sites-enabled/gislab-web-plugin state=link
  notify:
    - service nginx restart


# Logging
- name: Activate GIS.lab Web error logs checking
  lineinfile: dest=/etc/logcheck/logcheck.logfiles line="/var/log/nginx/gislab-web-error.log" state=present


# Backup
- name: Install storage backup script
  copy: src=static/bin/gislab-backup-web.sh dest=/etc/cron.d.bin/gislab-backup-web.sh mode=0755

- name: Activate user data backup
  template: src=cron/gislab-backup-web.j2 dest=/etc/cron.d/gislab-backup-web


- meta: flush_handlers
