---
#
### GIS.lab CLUSTER ###
#
# Install GIS.lab clustering support.
#
# Logging: syslog


- name: Install packages
  apt:
    pkg: "{{ item }}"
    force: yes
    install_recommends: no
    state: latest
  with_items:
    - unzip


- name: Purge GIS.lab cluster installation directory
  file:
    dest: "{{ root_dir }}"
    state: absent

- name: Prepare directory for cluster installation
  file:
    path: "{{ root_dir }}"
    state: directory


- name: Install Serf
  shell: >
    source {{ GISLAB_PATH_SYSTEM }}/functions.sh
    &&
    gislab_serf_install
  args:
    executable: /bin/bash


- name: Generate encryption key (run only once)
  shell: >
    echo -e "[\"$(serf keygen)\"]" > {{ GISLAB_PATH_SECRET }}/gislab_serf.key
    &&
    chmod 600 {{ GISLAB_PATH_SECRET }}/gislab_serf.key
  args:
    executable: /bin/bash
    creates: "{{ GISLAB_PATH_SECRET }}/gislab_serf.key"


- name: Prepare directory for cluster handlers
  file:
    path: "{{ root_dir }}/handlers"
    state: directory

- name: Install Serf handlers scripts
  copy:
    src: static/serf/
    dest: "{{ root_dir }}/handlers"
    mode: 0774
  notify:
  - service serf-agent restart


- name: Install Serf agent init script
  template:
    src: init/serf-agent.conf.j2
    dest: /etc/init/serf-agent.conf
  notify:
  - service serf-agent restart


- meta: flush_handlers

# vim: set ts=8 sts=2 sw=2 et:
