---

# I was trying to test DHCP server using udhcpc client and dhcping. It seems,
# that both can't work when client and server is the same machine:
# * $ busybox udhcpc -i eth1 -s /tmp/test.sh
# * $ dhcping -V -c 192.168.15.5 -s 192.168.15.5

- name: Test HTTP boot service
  shell: >
    curl http://localhost:6700/?ip=192.168.77.7
    | grep "kernel http://192.168.77.7/vmlinuz ro root=/dev/nbd0 init=/sbin/init-gislab"
  ignore_errors: yes
  changed_when: False

# vim: set ts=8 sts=2 sw=2 et:
