---

# I was trying to test DHCP server using udhcpc client and dhcping. It seems,
# that both can't work when client and server is the same machine:
# * $ busybox udhcpc -i eth1 -s /tmp/test.sh
# * $ dhcping -V -c 192.168.15.5 -s 192.168.15.5

- name: Test HTTP boot service
  shell: >
    curl http://localhost:6700/?ip=192.168.77.7
    | grep "kernel http://192.168.77.7/clients/desktop/vmlinuz"
  ignore_errors: yes
  changed_when: False

- name: Test if kernel is downloadable via HTTP
  shell: >
    curl http://localhost:6700
    | grep "[\s]*kernel"
    | curl -I $(awk -F " " '{print $2}')
    | grep "HTTP/1.1 200 OK"
  ignore_errors: yes
  changed_when: False

- name: Test if initrd is downloadable via HTTP
  shell: >
    curl http://localhost:6700
    | grep "[\s]*initrd"
    | curl -I $(awk -F " " '{print $2}')
    | grep "HTTP/1.1 200 OK"
  ignore_errors: yes
  changed_when: False

# vim: set ts=8 sts=2 sw=2 et:
