---
#
### ADMINISTRATOR USER ACCOUNT ###
#
# Create administrator user 'gislab' account if any password given on installation start. Update password
# if 'gislab' account already exists.


- name: Detect if GIS.lab administrator user account is already created
  shell: "id gislab || echo 'USER DOES NOT EXIST'"
  args:
    executable: /bin/bash
  register: admin_account_status
  changed_when: False

- name: Create GIS.lab administrator user account 'gislab'
  shell: "gislab-adduser -s -g {{ GISLAB_ADMIN_FIRST_NAME }} -l {{ GISLAB_ADMIN_SURNAME }} -m {{ GISLAB_ADMIN_EMAIL }} -p {{ GISLAB_ADMIN_PASSWORD }} gislab"
  when: GISLAB_ADMIN_PASSWORD != "" and admin_account_status.stdout == 'USER DOES NOT EXIST'

- name: Update GIS.lab administrator user account password
  shell: "gislab-password -p {{ GISLAB_ADMIN_PASSWORD }} gislab"
  when: GISLAB_ADMIN_PASSWORD != ""
