---
#
### ADMINISTRATOR USER ACCOUNT ###
#
# Create or update GIS.lab administrator user account 'gislab' with given or random password.


- name: Detect if GIS.lab administrator user account is already created
  shell: "id gislab || echo 'ADMIN DOES NOT EXIST'"
  args:
    executable: /bin/bash
  register: admin_account_status
  changed_when: False

- name: Create GIS.lab administrator user account 'gislab' if doesn't exist
  shell: gislab-adduser
    -s
    -g "{{ GISLAB_ADMIN_FIRST_NAME }}"
    -l "{{ GISLAB_ADMIN_SURNAME }} [GIS.lab ID{{ ":" }} {{ GISLAB_UNIQUE_ID }}]"
    -m "{{ GISLAB_ADMIN_EMAIL }}"
    gislab
  when: admin_account_status.stdout == 'ADMIN DOES NOT EXIST'


- name: Update password of GIS.lab administrator user account with given password
  shell: gislab-password
    -p "{{ GISLAB_ADMIN_PASSWORD }}"
    gislab
  when: GISLAB_ADMIN_PASSWORD != ""


# vim:ft=ansible:
