---
#
### ADMINISTRATOR USER ACCOUNT ###
#
# Create administrator user 'gislab' account if any password given on installation start. Update password
# if 'gislab' account already exists.


- name: Detect if GIS.lab administrator user account is already created
  shell: "id gislab || echo 'ADMIN DOES NOT EXIST'"
  args:
    executable: /bin/bash
  register: admin_account_status
  changed_when: False

- name: Create GIS.lab administrator user account 'gislab'
  shell: gislab-adduser
    -s
    -g "Administrator"
    -l "GIS.lab"
    -m "gislab@gis.lab"
    -p "{{ GISLAB_ADMIN_PASSWORD }}"
    gislab
  when: GISLAB_ADMIN_PASSWORD != "" and admin_account_status.stdout == 'ADMIN DOES NOT EXIST'

- name: Update password of GIS.lab administrator user account
  shell: gislab-password
    -p "{{ GISLAB_ADMIN_PASSWORD }}"
    gislab
  when: GISLAB_ADMIN_PASSWORD != ""


# vim:ft=ansible:
