---

- name: service nbd-server restart
  service:
    name: nbd-server
    state: restarted

- name: service gislab-http-boot restart
  service:
    name: gislab-http-boot
    state: restarted

# vim: set ts=8 sts=2 sw=2 et:
